specVersion: 0.2.0
name: HelloWorld-shibuya
version: 0.0.4
description: This SubQuery project can be use as a starting point for shibuya network
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://rpc.shibuya.astar.network'
  genesisHash: '0xddb89973361a170839f80f152d2e9e38a376a5a7eccefcade763f46a8e567019'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
